import { COLS, ROWS, ROTATIONS } from './constants.js';
import { collide } from './pieces.js';

// ---------------------------------------------------------------------------
// Weight loading
// weights.json is generated by train.py and served alongside the JS.
// Falls back to hard-coded defaults so the bot always works.
// ---------------------------------------------------------------------------

const DEFAULT_WEIGHTS = {
  HEIGHT_WEIGHT:       -0.51,
  HOLE_WEIGHT:         -0.75,
  COVERED_HOLE_WEIGHT: -0.50,
  BUMPINESS_WEIGHT:    -0.18,
  CLEAR_WEIGHT:         1.00,
  ATTACK_WEIGHT:        0.80,
  B2B_WEIGHT:           0.30,
  COMBO_WEIGHT:         0.20,
  TSPIN_WEIGHT:         0.40,
  SURVIVAL_WEIGHT:     -1.50,
  WELL_WEIGHT:          0.25,
  QUAD_BONUS:           1.00,
};

let W = { ...DEFAULT_WEIGHTS };

// Attempt to load weights.json once at startup (non-blocking).
fetch('./weights.json')
  .then(r => r.ok ? r.json() : null)
  .then(data => { if (data && data.weights) Object.assign(W, data.weights); })
  .catch(() => {});

// ---------------------------------------------------------------------------
// Board feature extraction
// ---------------------------------------------------------------------------

function colHeights(grid) {
  const h = new Int32Array(COLS);
  for (let c = 0; c < COLS; c++)
    for (let r = 0; r < ROWS; r++)
      if (grid[r][c]) { h[c] = ROWS - r; break; }
  return h;
}

function countHoles(grid) {
  let holes = 0, covered = 0;
  for (let c = 0; c < COLS; c++) {
    let blocksAbove = 0;
    for (let r = 0; r < ROWS; r++) {
      if (grid[r][c]) { blocksAbove++; }
      else if (blocksAbove > 0) { holes++; covered += blocksAbove - 1; }
    }
  }
  return [holes, covered];
}

function detectTspinSlots(heights) {
  let slots = 0;
  for (let c = 1; c < COLS - 1; c++) {
    const left  = heights[c - 1];
    const right = heights[c + 1];
    if (heights[c] + 2 <= left && heights[c] + 2 <= right) slots++;
  }
  return slots;
}

function detectWell(heights) {
  let best = 0;
  for (let c = 0; c < COLS; c++) {
    const left  = c > 0         ? heights[c - 1] : 20;
    const right = c < COLS - 1  ? heights[c + 1] : 20;
    const depth = Math.min(left, right) - heights[c];
    if (depth > best) best = depth;
  }
  return Math.min(best, 8);
}

function survivalPenalty(heights) {
  const maxH = Math.max(...heights);
  if (maxH >= ROWS - 5) return (maxH - (ROWS - 5)) ** 2;
  return 0;
}

// ---------------------------------------------------------------------------
// Evaluation
// ---------------------------------------------------------------------------

// Attack sent for a given clear (non-T-spin path, T-spin doubles values)
const ATTACK_TABLE = [[0, 0, 1, 2, 4], [0, 2, 4, 6, 8]]; // [spin][lines]

function b2bBonus(b2b) {
  if (b2b <= 0)  return 0;
  if (b2b <= 2)  return 0.5;
  if (b2b <= 5)  return 1;
  if (b2b <= 10) return 2;
  return 3;
}

function evalBoard(grid, cleared, spin, combo, b2b) {
  const heights = colHeights(grid);
  const agg     = heights.reduce((a, v) => a + v, 0);
  const [holes, covered] = countHoles(grid);
  let bump = 0;
  for (let c = 0; c < COLS - 1; c++) bump += Math.abs(heights[c] - heights[c + 1]);
  const tspinVal = detectTspinSlots(heights);
  const wellVal  = detectWell(heights);
  const survPen  = survivalPenalty(heights);

  // Attack reward
  const spinIdx  = spin ? 1 : 0;
  let baseAtk    = ATTACK_TABLE[spinIdx][Math.min(cleared, 4)];
  const isB2B    = cleared >= 4 || (spin && cleared > 0);
  if (isB2B) baseAtk += b2bBonus(b2b);
  const attack   = Math.floor(baseAtk * (1 + 0.2 * combo));

  // Line-clear reward (exponential so quads >> singles)
  const clearRewards = [0, 0.5, 1.0, 2.0, 4.0];
  let clearReward = clearRewards[Math.min(cleared, 4)];
  if (cleared === 4) clearReward += W.QUAD_BONUS;

  return (
    W.HEIGHT_WEIGHT       * agg
    + W.HOLE_WEIGHT       * holes
    + W.COVERED_HOLE_WEIGHT * covered
    + W.BUMPINESS_WEIGHT  * bump
    + W.CLEAR_WEIGHT      * clearReward
    + W.ATTACK_WEIGHT     * attack
    + W.B2B_WEIGHT        * (isB2B ? 1 : 0)
    + W.COMBO_WEIGHT      * combo
    + W.TSPIN_WEIGHT      * tspinVal
    + W.SURVIVAL_WEIGHT   * survPen
    + W.WELL_WEIGHT       * wellVal
  );
}

// ---------------------------------------------------------------------------
// Board simulation helpers
// ---------------------------------------------------------------------------

function simulateDrop(grid, shape, x) {
  let y = 0;
  while (!collide(shape, x, y + 1, grid)) y++;
  return y;
}

function applyPlacement(grid, shape, x, y) {
  const g = grid.map(r => r.slice());
  for (let r = 0; r < shape.length; r++)
    for (let c = 0; c < shape[r].length; c++)
      if (shape[r][c] && y + r >= 0 && y + r < ROWS)
        g[y + r][x + c] = '#ai';
  return g;
}

function clearLines(grid) {
  const kept = grid.filter(row => !row.every(c => c));
  const cleared = ROWS - kept.length;
  while (kept.length < ROWS) kept.unshift(new Array(COLS).fill(null));
  return [kept, cleared];
}

// ---------------------------------------------------------------------------
// T-spin detection helper (immobility test after kick)
// ---------------------------------------------------------------------------

function isTspin(shape, x, y, grid) {
  // Simplified: immobility test (can't move left/right/up)
  return (
    collide(shape, x - 1, y, grid) &&
    collide(shape, x + 1, y, grid) &&
    collide(shape, x,     y - 1, grid)
  );
}

// ---------------------------------------------------------------------------
// Move generator — returns all reachable (rot, x, y) placements
// ---------------------------------------------------------------------------

function genPlacements(grid, key) {
  const placements = [];
  const seen = new Set();
  for (let rot = 0; rot < 4; rot++) {
    const shape = ROTATIONS[key][rot];
    const w = shape[0].length;
    for (let x = -1; x <= COLS - w + 1; x++) {
      if (collide(shape, x, 0, grid)) continue;
      const y = simulateDrop(grid, shape, x);
      const sig = `${rot},${x},${y}`;
      if (seen.has(sig)) continue;
      seen.add(sig);
      placements.push({ rot, x, y, shape });
    }
  }
  return placements;
}

// ---------------------------------------------------------------------------
// Beam search
// ---------------------------------------------------------------------------

const BEAM_WIDTH   = 100;
const SEARCH_DEPTH = 3;   // pieces ahead

// A node in the search tree
// { grid, combo, b2b, score, rootRot, rootX, rootY }

function beamSearch(grid, currentKey, queue, holdKey, combo, b2b) {
  // Initial beam: expand current piece + hold option.
  // When hold is empty (null) we can still hold the current piece and pull the
  // next queued piece — model this as a virtual hold key of queue[0].
  const keysToTry = holdKey !== null
    ? [currentKey, holdKey]
    : (queue.length > 0 ? [currentKey, null] : [currentKey]);

  let beam = [];

  for (const tryKeyRaw of keysToTry) {
    // tryKeyRaw === null means "hold current into empty slot, use queue[0] now"
    const isHold   = tryKeyRaw !== currentKey;
    const tryKey   = isHold && tryKeyRaw === null ? queue[0] : (tryKeyRaw ?? currentKey);
    // After holding into empty slot, queue shifts by one (currentKey goes to hold)
    const nextQueue = isHold && holdKey === null
      ? [currentKey, ...queue.slice(1)]
      : queue;

    for (const { rot, x, y, shape } of genPlacements(grid, tryKey)) {
      const g2 = applyPlacement(grid, shape, x, y);
      const [g3, cleared] = clearLines(g2);
      const spin = tryKey === 'T' && cleared > 0 && isTspin(shape, x, y, grid);
      const newCombo = cleared > 0 ? combo + 1 : 0;
      const newB2b   = (cleared >= 4 || spin) ? b2b + 1 : (cleared > 0 ? 0 : b2b);
      const sc = evalBoard(g3, cleared, spin, newCombo, newB2b);

      beam.push({
        grid: g3,
        combo: newCombo,
        b2b:   newB2b,
        score: sc,
        rootRot:  rot,
        rootX:    x,
        rootY:    y,
        rootHold: isHold,
        nextQueue,
      });
    }
  }

  if (beam.length === 0) return null;

  // Prune initial beam
  beam.sort((a, b) => b.score - a.score);
  beam = beam.slice(0, BEAM_WIDTH);

  // Expand for SEARCH_DEPTH - 1 more pieces
  for (let depth = 1; depth < SEARCH_DEPTH; depth++) {
    const next = [];
    for (const node of beam) {
      const key = node.nextQueue[depth - 1];
      if (!key) continue;
      for (const { x, y, shape } of genPlacements(node.grid, key)) {
        const g2 = applyPlacement(node.grid, shape, x, y);
        const [g3, cleared] = clearLines(g2);
        const spin = key === 'T' && cleared > 0 && isTspin(shape, x, y, node.grid);
        const nc = cleared > 0 ? node.combo + 1 : 0;
        const nb = (cleared >= 4 || spin) ? node.b2b + 1 : (cleared > 0 ? 0 : node.b2b);
        const sc = evalBoard(g3, cleared, spin, nc, nb);
        next.push({
          grid: g3, combo: nc, b2b: nb,
          score: node.score + sc,
          rootRot:   node.rootRot,
          rootX:     node.rootX,
          rootY:     node.rootY,
          rootHold:  node.rootHold,
          nextQueue: node.nextQueue,
        });
      }
    }
    if (next.length === 0) break;
    next.sort((a, b) => b.score - a.score);
    beam = next.slice(0, BEAM_WIDTH);
  }

  beam.sort((a, b) => b.score - a.score);
  return beam[0];
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * computeBestMove(grid, key, queue?, holdKey?, combo?, b2b?)
 *
 * Returns { rot, x, y, hold, valid }.
 *
 * Maintains backward compatibility: when called with just (grid, key) it
 * falls through to the depth-1 search used by the old API.
 */
export function computeBestMove(grid, key, queue = [], holdKey = null, combo = 0, b2b = 0) {
  const result = beamSearch(grid, key, queue, holdKey, combo, b2b);

  if (!result) {
    // No valid placement found — game over
    return { rot: 0, x: Math.floor(COLS / 2) - 1, y: 0, hold: false, valid: false };
  }

  return {
    rot:   result.rootRot,
    x:     result.rootX,
    y:     result.rootY,
    hold:  result.rootHold,
    valid: true,
  };
}
