// Sleeping Slaves — NN-based bot (distilled from Diver Down heuristic)
// Architecture: 228 → 128 → 64 → 1   (ReLU hidden layers)
// Weights loaded from nn_weights.json (generated by train_nn.py)

import { COLS, ROWS, ROTATIONS } from './constants.js';
import { collide } from './pieces.js';

// ── Weight loading ────────────────────────────────────────────────────────────

let nnLayers = null;   // [{W: Float32Array, b: Float32Array, fanIn, fanOut}]
let nnReady  = false;

fetch('./nn_weights.json')
  .then(r => r.ok ? r.json() : null)
  .then(data => {
    if (!data || !data.params) return;
    nnLayers = data.params.map(p => {
      const fanIn  = p.W.length;
      const fanOut = p.W[0].length;
      // Store W in row-major flat array (W[i*fanOut + j])
      const W = new Float32Array(fanIn * fanOut);
      let idx = 0;
      for (let i = 0; i < fanIn; i++)
        for (let j = 0; j < fanOut; j++)
          W[idx++] = p.W[i][j];
      return { W, b: new Float32Array(p.b), fanIn, fanOut };
    });
    nnReady = true;
  })
  .catch(() => {});

// ── Feature extraction — matches extract_features() in train_nn.py ────────────
// Output: Float32Array(228)
//   [0..199]   raw binary cells (row-major)
//   [200..209] normalised column heights  (h[c] / ROWS)
//   [210..219] normalised per-col holes   (holeCnt[c] / ROWS)
//   [220..227] aggregate scalars: agg, bump, max_h, holes_n, covered_n, well, ts, surv

function extractFeatures(grid) {
  const f = new Float32Array(228);
  let fi = 0;

  // 200 raw binary cells
  for (let r = 0; r < ROWS; r++)
    for (let c = 0; c < COLS; c++)
      f[fi++] = grid[r][c] ? 1.0 : 0.0;

  // Column heights
  const h = new Int32Array(COLS);
  for (let c = 0; c < COLS; c++)
    for (let r = 0; r < ROWS; r++)
      if (grid[r][c]) { h[c] = ROWS - r; break; }

  // Normalised heights
  for (let c = 0; c < COLS; c++) f[fi++] = h[c] / ROWS;

  // Per-column hole count (normalised)
  const holeCnt = new Int32Array(COLS);
  for (let c = 0; c < COLS; c++) {
    let above = 0;
    for (let r = 0; r < ROWS; r++) {
      if (grid[r][c]) above++;
      else if (above > 0) holeCnt[c]++;
    }
    f[fi++] = holeCnt[c] / ROWS;
  }

  // Aggregate scalars
  let agg = 0;
  for (let c = 0; c < COLS; c++) agg += h[c];
  f[fi++] = agg / (ROWS * COLS);

  let bump = 0;
  for (let c = 0; c < COLS - 1; c++) bump += Math.abs(h[c] - h[c + 1]);
  f[fi++] = bump / (ROWS * COLS);

  let maxH = 0;
  for (let c = 0; c < COLS; c++) if (h[c] > maxH) maxH = h[c];
  f[fi++] = maxH / ROWS;

  let holes = 0, covered = 0;
  for (let c = 0; c < COLS; c++) {
    let above = 0;
    for (let r = 0; r < ROWS; r++) {
      if (grid[r][c]) above++;
      else if (above > 0) { holes++; covered += above - 1; }
    }
  }
  f[fi++] = holes   / (ROWS * COLS);
  f[fi++] = covered / (ROWS * COLS);

  // Well depth (deepest single well, capped at 8)
  let well = 0;
  for (let c = 0; c < COLS; c++) {
    const left  = c > 0       ? h[c - 1] : 20;
    const right = c < COLS-1  ? h[c + 1] : 20;
    const d = Math.min(left, right) - h[c];
    if (d > well) well = d;
  }
  f[fi++] = Math.min(well, 8) / 8.0;

  // T-spin slots
  let ts = 0;
  for (let c = 1; c < COLS - 1; c++)
    if (h[c] + 2 <= h[c - 1] && h[c] + 2 <= h[c + 1]) ts++;
  f[fi++] = ts / COLS;

  // Survival penalty
  const surv = maxH >= ROWS - 5 ? (maxH - (ROWS - 5)) ** 2 : 0;
  f[fi++] = surv / (ROWS * ROWS);

  return f;
}

// ── NN forward pass ────────────────────────────────────────────────────────────

function nnEval(grid) {
  const feats = extractFeatures(grid);
  let a = feats;
  const last = nnLayers.length - 1;
  for (let l = 0; l <= last; l++) {
    const { W, b, fanIn, fanOut } = nnLayers[l];
    const z = b.slice();  // start with bias
    // Cache-friendly: accumulate row i's contribution to all outputs
    for (let i = 0; i < fanIn; i++) {
      const ai = a[i];
      if (ai === 0) continue;          // skip zero activations
      const base = i * fanOut;
      for (let j = 0; j < fanOut; j++) z[j] += ai * W[base + j];
    }
    // ReLU on hidden layers, linear on output
    if (l < last) for (let j = 0; j < fanOut; j++) if (z[j] < 0) z[j] = 0;
    a = z;
  }
  return a[0];
}

// ── Board simulation (same helpers as ai.js) ──────────────────────────────────

function simulateDrop(grid, shape, x) {
  let y = 0;
  while (!collide(shape, x, y + 1, grid)) y++;
  return y;
}

function applyPlacement(grid, shape, x, y) {
  const g = grid.map(r => r.slice());
  for (let r = 0; r < shape.length; r++)
    for (let c = 0; c < shape[r].length; c++)
      if (shape[r][c] && y + r >= 0 && y + r < ROWS)
        g[y + r][x + c] = 1;   // binary 1 matches training data format
  return g;
}

function clearLines(grid) {
  const kept = grid.filter(row => !row.every(c => c));
  const cleared = ROWS - kept.length;
  while (kept.length < ROWS) kept.unshift(new Array(COLS).fill(null));
  return [kept, cleared];
}

function genPlacements(grid, key) {
  const out = [], seen = new Set();
  for (let rot = 0; rot < 4; rot++) {
    const shape = ROTATIONS[key][rot];
    const w = shape[0].length;
    for (let x = -1; x <= COLS - w + 1; x++) {
      if (collide(shape, x, 0, grid)) continue;
      const y = simulateDrop(grid, shape, x);
      const sig = `${rot},${x},${y}`;
      if (seen.has(sig)) continue;
      seen.add(sig);
      out.push({ rot, x, y, shape });
    }
  }
  return out;
}

// ── Beam search (width 25, depth 2) ───────────────────────────────────────────
// Smaller than Diver Down (100/3) to keep NN inference within frame budget.

const BEAM_WIDTH = 25;
const DEPTH      = 2;

function nnBeamSearch(grid, key, queue, holdKey, combo, b2b) {
  const keysToTry = holdKey !== null
    ? [key, holdKey]
    : (queue.length > 0 ? [key, null] : [key]);

  let beam = [];

  for (const tryRaw of keysToTry) {
    const isHold  = tryRaw !== key;
    const tryKey  = isHold && tryRaw === null ? queue[0] : (tryRaw ?? key);
    const nq = isHold && holdKey === null ? [key, ...queue.slice(1)] : queue;

    for (const { rot, x, y, shape } of genPlacements(grid, tryKey)) {
      const g2 = applyPlacement(grid, shape, x, y);
      const [g3, cleared] = clearLines(g2);
      const sc = nnEval(g3);
      beam.push({ grid: g3, score: sc, rootRot: rot, rootX: x, rootY: y, rootHold: isHold, nq });
    }
  }

  if (!beam.length) return null;
  beam.sort((a, b) => b.score - a.score);
  beam = beam.slice(0, BEAM_WIDTH);

  for (let d = 1; d < DEPTH; d++) {
    const next = [];
    for (const node of beam) {
      const k = node.nq[d - 1];
      if (!k) continue;
      for (const { x, y, shape } of genPlacements(node.grid, k)) {
        const g2 = applyPlacement(node.grid, shape, x, y);
        const [g3, cleared] = clearLines(g2);
        const sc = nnEval(g3);
        next.push({
          grid: g3, score: node.score + sc,
          rootRot: node.rootRot, rootX: node.rootX, rootY: node.rootY,
          rootHold: node.rootHold, nq: node.nq,
        });
      }
    }
    if (!next.length) break;
    next.sort((a, b) => b.score - a.score);
    beam = next.slice(0, BEAM_WIDTH);
  }

  beam.sort((a, b) => b.score - a.score);
  return beam[0];
}

// ── Fallback heuristic (used while weights are loading) ───────────────────────

function fallbackScore(grid) {
  let agg = 0, holes = 0;
  const h = new Int32Array(COLS);
  for (let c = 0; c < COLS; c++)
    for (let r = 0; r < ROWS; r++)
      if (grid[r][c]) { h[c] = ROWS - r; break; }
  for (let c = 0; c < COLS; c++) agg += h[c];
  for (let c = 0; c < COLS; c++) {
    let above = 0;
    for (let r = 0; r < ROWS; r++) {
      if (grid[r][c]) above++;
      else if (above > 0) holes++;
    }
  }
  let bump = 0;
  for (let c = 0; c < COLS - 1; c++) bump += Math.abs(h[c] - h[c + 1]);
  return -0.51 * agg - 0.75 * holes - 0.18 * bump;
}

function fallbackMove(grid, key) {
  let best = -Infinity, bestNode = null;
  for (const { rot, x, y, shape } of genPlacements(grid, key)) {
    const g2 = applyPlacement(grid, shape, x, y);
    const [g3] = clearLines(g2);
    const sc = fallbackScore(g3);
    if (sc > best) { best = sc; bestNode = { rot, x, y }; }
  }
  if (!bestNode) return { rot: 0, x: Math.floor(COLS / 2) - 1, y: 0, hold: false, valid: false };
  return { ...bestNode, hold: false, valid: true };
}

// ── Public API (same signature as ai.js) ─────────────────────────────────────

export function computeBestMove(grid, key, queue = [], holdKey = null, combo = 0, b2b = 0) {
  if (!nnReady) return fallbackMove(grid, key);

  const result = nnBeamSearch(grid, key, queue, holdKey, combo, b2b);
  if (!result) return { rot: 0, x: Math.floor(COLS / 2) - 1, y: 0, hold: false, valid: false };

  return { rot: result.rootRot, x: result.rootX, y: result.rootY, hold: result.rootHold, valid: true };
}
